declare let input: string;
declare let inputArr: string[];
declare let lines: string[];
declare const add: (a: number, b: number) => number;
declare const desc: (a: number, b: number) => number;
declare const asc: (a: number, b: number) => number;
declare const log: (...args: any) => void;
declare const log1: (arg: any) => void;
declare const log2: (arg: any) => void;
declare const toNumber: (str: string) => number;
declare const toNumbers: (str: string) => number[];
declare const pairs: <T>(arr: T[]) => T[][];
declare const ic: <T>(arr: T[]) => (readonly [T, number])[];
declare const reverse: <T>(arr: T[]) => T[];
