declare var input: string;
declare var inputArr: string[];
declare var lines: string[];
declare var add: (a: number, b: number) => number;
declare var desc: (a: number, b: number) => number;
declare var asc: (a: number, b: number) => number;
declare var log: (...args: any) => void;
declare var log1: (arg: any) => void;
declare var log2: (arg: any) => void;
declare var toNumber: (str: string) => number;
declare var toNumbers: (str: string) => number[];
